# Applications of MLP

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Churn Analysis
---
- Churn refers to the number of customers who stop doing business with a company within a given time period. <br><br>
- A high churn rate can be a sign of customer dissatisfaction or a problem with the company's products or services. It can also be caused by factors outside of the company's control, such as a competitor offering a better deal.<br><br>
- Churning customers can have a number of economic disadvantages for a business, including:<br>
    - Loss of revenue. When customers churn, they stop paying for the company's products or services. This can lead to a significant loss of revenue, especially for businesses that rely on recurring revenue.<br><br>
    - Increased marketing costs. To replace lost customers, businesses often need to spend more on marketing and sales. This can be a significant expense, especially for businesses with a high churn rate.<br><br>
    - Damage to brand reputation. When customers churn, they may spread negative word-of-mouth about the company. This can damage the company's brand reputation and make it more difficult to attract new customers.<br><br>
    - Increased customer acquisition costs. It is more expensive to acquire new customers than to retain existing customers. This is because new customers are less likely to be familiar with the company's products or services and may require more hand-holding.<br><br>
    - Decreased customer lifetime value. The customer lifetime value (CLV) is the total amount of money that a customer is expected to spend with a company over their lifetime. When customers churn, the company loses out on the potential future revenue that they could have generated from that customer.<br><br>

- The economic disadvantages of churning customers can be significant, so it is important for businesses to take steps to reduce churn. Some common ways to reduce churn include:<br><br>

    - Providing excellent customer service. This means being responsive to customer inquiries, resolving problems quickly and efficiently, and going the extra mile to make sure that customers are satisfied.<br><br>
    - Offering competitive prices. This means keeping prices in line with the competition and offering discounts and promotions to encourage customers to stay with the company.<br><br>
    - Constantly innovating. This means keeping up with the latest trends and offering new and improved products and services to keep customers engaged.<br><br>
    - Personalizing the customer experience. This means getting to know each customer's individual needs and preferences and tailoring the company's offerings accordingly.
<br><br>
- By taking steps to reduce churn, businesses can improve their bottom line and ensure long-term success.

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('bank_data.csv')

In [ ]:
dataset

In [ ]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
pd.DataFrame(X, columns = ["CreditScore","Geography","Gender","Age","Tenure","Balance","NumOfProducts","HasCrCard","IsActiveMember","EstimatedSalary"])

In [ ]:
pd.DataFrame(y, columns = ["Exited"])

In [ ]:
X

In [ ]:
y

### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer


In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)
accuracy_score(y_test, y_pred)

In [ ]:
fig, ax = plt.subplots(figsize=(7.5, 7.5))
ax.matshow(conf_matrix, cmap=plt.cm.Blues, alpha=0.3)
for i in range(conf_matrix.shape[0]):
    for j in range(conf_matrix.shape[1]):
        ax.text(x=j, y=i,s=conf_matrix[i, j], va='center', ha='center', size='xx-large')
 
plt.xlabel('Predictions', fontsize=18)
plt.ylabel('Actuals', fontsize=18)
plt.title('Confusion Matrix', fontsize=18)
plt.show()

**Homework**
- Use the dataset: https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset.
- Experiment with the number of hidden layers, and the number of units in the hidden layer.
- Try to experiment on the activation functions in the hidden layer https://www.tensorflow.org/api_docs/python/tf/keras/activations
- Try to experiment with the optimizer: https://www.tensorflow.org/api_docs/python/tf/keras/optimizers
- Check the accuracy, specificity, and sensitivity of your model.

## Data Preprocessing

In [3]:
dataset = pd.read_csv('diabetes_prediction_dataset.csv')
dataset

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [4]:
X = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,-1].values

In [5]:
pd.DataFrame(X, columns = ["gender", "age", "hypertension", "heart_disease","smoking_history", "bmi", "HbA1c_level", "blood_glucose_level"])

gender   age hypertension heart_disease smoking_history    bmi  \
0      Female  80.0            0             1           never  25.19   
1      Female  54.0            0             0         No Info  27.32   
2        Male  28.0            0             0           never  27.32   
3      Female  36.0            0             0         current  23.45   
4        Male  76.0            1             1         current  20.14   
...       ...   ...          ...           ...             ...    ...   
99995  Female  80.0            0             0         No Info  27.32   
99996  Female   2.0            0             0         No Info  17.37   
99997    Male  66.0            0             0          former  27.83   
99998  Female  24.0            0             0           never  35.42   
99999  Female  57.0            0             0         current  22.43   

      HbA1c_level blood_glucose_level  
0             6.6                 140  
1             6.6                  80  
2             5.7                 158  
3             5.0                 155  
4             4.8                 155  
...           ...                 ...  
99995         6.2                  90  
99996         6.5                 100  
99997         5.7                 155  
99998         4.0                 100  
99999         6.6                  90  

[100000 rows x 8 columns]

In [6]:
pd.DataFrame(y, columns = ["diabetes"])

diabetes
0             0
1             0
2             0
3             0
4             0
...         ...
99995         0
99996         0
99997         0
99998         0
99999         0

[100000 rows x 1 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])
print(X)

[[0 80.0 0 ... 25.19 6.6 140]
 [0 54.0 0 ... 27.32 6.6 80]
 [1 28.0 0 ... 27.32 5.7 158]
 ...
 [1 66.0 0 ... 27.83 5.7 155]
 [0 24.0 0 ... 35.42 4.0 100]
 [0 57.0 0 ... 22.43 6.6 90]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 0.0 ... 25.19 6.6 140]
 [1.0 0.0 0.0 ... 27.32 6.6 80]
 [0.0 0.0 0.0 ... 27.32 5.7 158]
 ...
 [0.0 0.0 0.0 ... 27.83 5.7 155]
 [0.0 0.0 0.0 ... 35.42 4.0 100]
 [0.0 1.0 0.0 ... 22.43 6.6 90]]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

In [11]:
ann = tf.keras.models.Sequential()

In [12]:
# 1st hidden layer
ann.add(tf.keras.layers.Dense(units=4, activation='elu'))

# 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=4, activation='elu'))

# 3rd hidden layer
ann.add(tf.keras.layers.Dense(units=4, activation='elu'))

# output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

In [13]:
ann.compile(optimizer = 'RMSprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
2500/2500 [==============================] - 4s 1ms/step - loss: 0.1541 - accuracy: 0.9477
Epoch 2/100
2500/2500 [==============================] - 4s 2ms/step - loss: 0.1160 - accuracy: 0.9594
Epoch 3/100
2500/2500 [==============================] - 4s 1ms/step - loss: 0.1155 - accuracy: 0.9593
Epoch 4/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.1152 - accuracy: 0.9596
Epoch 5/100
2500/2500 [==============================] - 5s 2ms/step - loss: 0.1150 - accuracy: 0.9598
Epoch 6/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.1149 - accuracy: 0.9596
Epoch 7/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.1147 - accuracy: 0.9600
Epoch 8/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.1144 - accuracy: 0.9603
Epoch 9/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.1142 - accuracy: 0.9599
Epoch 10/100
2500/2500 [==============================] - 3s 1ms/step - l

## Making the predictions and evaluating the model

In [15]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

625/625 [==============================] - 1s 984us/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

tn, fp, fn, tp = conf_matrix.ravel()

specificity = tn / (tn + fp)
sensitivity = tp / (tp + fn)

print('accuracy:', accuracy_score(y_test, y_pred))

print('specificty:', sensitivity)

print('sensitivity:', sensitivity)

[[18267    30]
 [  565  1138]]
accuracy: 0.97025
specificty: 0.6682325308279506
sensitivity: 0.6682325308279506
