## Imports

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Data Preprocessing

In [3]:
dataset = pd.read_csv('diabetes_prediction_dataset.csv')
dataset

gender   age  hypertension  heart_disease smoking_history    bmi   
0      Female  80.0             0              1           never  25.19  \
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [4]:
X = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,-1].values

In [5]:
pd.DataFrame(X, columns = ["gender", "age", "hypertension", "heart_disease","smoking_history", "bmi", "HbA1c_level", "blood_glucose_level"])

gender   age hypertension heart_disease smoking_history    bmi   
0      Female  80.0            0             1           never  25.19  \
1      Female  54.0            0             0         No Info  27.32   
2        Male  28.0            0             0           never  27.32   
3      Female  36.0            0             0         current  23.45   
4        Male  76.0            1             1         current  20.14   
...       ...   ...          ...           ...             ...    ...   
99995  Female  80.0            0             0         No Info  27.32   
99996  Female   2.0            0             0         No Info  17.37   
99997    Male  66.0            0             0          former  27.83   
99998  Female  24.0            0             0           never  35.42   
99999  Female  57.0            0             0         current  22.43   

      HbA1c_level blood_glucose_level  
0             6.6                 140  
1             6.6                  80  
2             5.7                 158  
3             5.0                 155  
4             4.8                 155  
...           ...                 ...  
99995         6.2                  90  
99996         6.5                 100  
99997         5.7                 155  
99998         4.0                 100  
99999         6.6                  90  

[100000 rows x 8 columns]

In [6]:
pd.DataFrame(y, columns = ["diabetes"])

diabetes
0             0
1             0
2             0
3             0
4             0
...         ...
99995         0
99996         0
99997         0
99998         0
99999         0

[100000 rows x 1 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])
print(X)

[[0 80.0 0 ... 25.19 6.6 140]
 [0 54.0 0 ... 27.32 6.6 80]
 [1 28.0 0 ... 27.32 5.7 158]
 ...
 [1 66.0 0 ... 27.83 5.7 155]
 [0 24.0 0 ... 35.42 4.0 100]
 [0 57.0 0 ... 22.43 6.6 90]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 0.0 ... 25.19 6.6 140]
 [1.0 0.0 0.0 ... 27.32 6.6 80]
 [0.0 0.0 0.0 ... 27.32 5.7 158]
 ...
 [0.0 0.0 0.0 ... 27.83 5.7 155]
 [0.0 0.0 0.0 ... 35.42 4.0 100]
 [0.0 1.0 0.0 ... 22.43 6.6 90]]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

In [13]:
ann = tf.keras.models.Sequential()

In [15]:
# 1st hidden layer
ann.add(tf.keras.layers.Dense(units=4, activation='elu'))

# 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=4, activation='elu'))

# 3rd hidden layer
ann.add(tf.keras.layers.Dense(units=4, activation='elu'))

# output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

In [16]:
ann.compile(optimizer = 'RMSprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
2500/2500 [==============================] - 6s 2ms/step - loss: 0.1504 - accuracy: 0.9485
Epoch 2/100
2500/2500 [==============================] - 4s 2ms/step - loss: 0.1186 - accuracy: 0.9593
Epoch 3/100
2500/2500 [==============================] - 4s 1ms/step - loss: 0.1174 - accuracy: 0.9601
Epoch 4/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.1169 - accuracy: 0.9600
Epoch 5/100
2500/2500 [==============================] - 4s 2ms/step - loss: 0.1164 - accuracy: 0.9602
Epoch 6/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.1165 - accuracy: 0.9597
Epoch 7/100
2500/2500 [==============================] - 3s 1ms/step - loss: 0.1161 - accuracy: 0.9598
Epoch 8/100
2500/2500 [==============================] - 4s 1ms/step - loss: 0.1163 - accuracy: 0.9598
Epoch 9/100
2500/2500 [==============================] - 4s 1ms/step - loss: 0.1162 - accuracy: 0.9597
Epoch 10/100
2500/2500 [==============================] - 4s 2ms/step - l

## Making the predictions and evaluating the model

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

625/625 [==============================] - 1s 1ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

tn, fp, fn, tp = conf_matrix.ravel()

specificity = tn / (tn + fp)
sensitivity = tp / (tp + fn)

print('accuracy:', accuracy_score(y_test, y_pred))

print('specificty:', sensitivity)

print('sensitivity:', sensitivity)

[[18252    45]
 [  633  1070]]
accuracy: 0.9661
specificty: 0.6283029947152085
sensitivity: 0.6283029947152085
